/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#faf9f7',
        'surface-dim': '#dadad8',
        'surface-bright': '#faf9f7',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f3f1',
        'surface-container': '#efeeec',
        'surface-container-high': '#e9e8e6',
        'surface-container-highest': '#e3e2e0',
        'on-surface': '#1a1c1b',
        'on-surface-variant': '#44474c',
        'inverse-surface': '#2f3130',
        'inverse-on-surface': '#f1f1ef',
        outline: '#75777c',
        'outline-variant': '#c5c6cc',
        'surface-tint': '#555f6f',
        primary: '#0a1422',
        'on-primary': '#ffffff',
        'primary-container': '#1f2937',
        'on-primary-container': '#8690a1',
        'inverse-primary': '#bdc7d9',
        secondary: '#546254',
        'on-secondary': '#ffffff',
        'secondary-container': '#d7e7d5',
        'on-secondary-container': '#5a685a',
        tertiary: '#250d05',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#3d2117',
        'on-tertiary-container': '#b08678',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#d9e3f6',
        'primary-fixed-dim': '#bdc7d9',
        'on-primary-fixed': '#121c2a',
        'on-primary-fixed-variant': '#3d4756',
        'secondary-fixed': '#d7e7d5',
        'secondary-fixed-dim': '#bbcbba',
        'on-secondary-fixed': '#121e14',
        'on-secondary-fixed-variant': '#3c4a3d',
        'tertiary-fixed': '#ffdbcf',
        'tertiary-fixed-dim': '#ebbcac',
        'on-tertiary-fixed': '#2e150b',
        'on-tertiary-fixed-variant': '#603f33',
        background: '#faf9f7',
        'on-background': '#1a1c1b',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      spacing: {
        unit: '4px',
        gutter: '16px',
        'margin-page': '24px',
        'container-padding': '12px',
        'sidebar-width': '280px',
        'ticket-width': '360px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
      },
      boxShadow: {
        'premium': '0 4px 20px -2px rgba(0, 0, 0, 0.05), 0 0 3px rgba(0,0,0,0.02)',
        'hover': '0 12px 30px -4px rgba(0, 0, 0, 0.1), 0 4px 10px rgba(0,0,0,0.04)',
        'inner-light': 'inset 0 2px 4px 0 rgba(255, 255, 255, 0.3)',
      },
      backgroundImage: {
        'glass-gradient': 'linear-gradient(135deg, rgba(255,255,255,0.8) 0%, rgba(255,255,255,0.4) 100%)',
      }
    },
  },
  plugins: [],
}
